[project]
name = "2026w-dight360"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "matplotlib>=3.10.8",
    "nltk>=3.9.2",
    "numpy>=2.4.1",
    "spacy>=3.8.11",
]
